import Nav from "../../Componentes/nav";
import Head from 'next/head';

export default function Sedes() {
    return (<>
        <Head>
        <title>Locomotor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>
        <Nav>
        </Nav>
        <main className="main-container">
        <div>Esto es Sedes</div>
        </main>
        <style jsx>{`

                	

                .main-container{

                    color: black;
                    font-size: 30px;
                    padding-top: 20px;
                    display: flex;
                    align-items: center;
                    justify-content:center;
                }            
            
            `}
        </style>
        
    </>)
}