import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Nav from "../Componentes/nav";
import Slider from "../Componentes/slider";

export default function Home() {

  


  return (
    <div className={styles.container}>
      <Head>
        <title>Locomotor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>
      <Nav></Nav>
      <Slider texto="Testimonio 1"></Slider>
      <Slider texto="Testimonio 2"></Slider>
      <Slider texto="Testimonio 3"></Slider>
      <Slider texto="Testimonio 4"></Slider>
    </div> 
  );
}
